# Generated by Django 6.0.3 on 2026-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profession",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
